[package]
name = "sdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type=["cdylib"]

[dev-dependencies]
rand = "0.8.5"
libc = "0.2.149"
nalgebra = "0.32.3"

[profile.release]
lto = true

